### ISSUE TITLE
Inconsistency example in readme with actual code.

### ISSUE THREAD

**Issue by alexcamlo** [inuitcss/trumps.spacing-responsive#12]
At the readme the example say to write classes as -> .lap-mb0, .desk-mb++

To actually use this trump you have to write classes as -> .u-mb0-lap, .u-mb++-desk

**Comment by ryanirilli** [comment]
+1 the pattern is not consistent either
for example, @thewinger is correct, it's `.u-mb0-lap`
but as you go down the file, it switches to `.u-palm-pt0`

Is there a reason for this?

**Comment by nenadjelovac** [comment]
Hm, I think something happened in [this commit](https://github.com/inuitcss/trumps.spacing-responsive/commit/0fbf0bee71a498ecb33b65f722f528743a25ccee) (probably by accident). @csswizardry can you please check this out. 

Thank you

**Comment by csshugs** [comment]
@thewinger @csswizardry @nenadjelovac 
So this issue can be closed for now?

**Comment by alexcamlo** [comment]
Yes

**Comment by csshugs** [comment]
:+1: Thanks
