### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by mikemjharris** [inuitcss/trumps.spacing-responsive#17]
Hi Harry,  

We like the refactoring in version 0.0.8 - the naming makes much more sense.  It doesn't look like you've released that to npm (still 0.0.7 there) - any chance you can push it up?  For now we're pointing at github but would be great to have it on npm too.

Cheers

Mike

**Comment by dennisfrank** [comment]
Maybe @anselmh can update NPM?

**Comment by anselmh** [comment]
`0.0.8` is now on npmjs: https://www.npmjs.com/package/inuit-responsive-spacing

Thanks for notifying, and I’m sorry this has been unnoticed so long.

**Comment by mikemjharris** [comment]
Thank you!
